parameters:
#    acme_account.example.class: Acme\AccountBundle\Example

services:
#    acme_account.example:
#        class: %acme_account.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
